apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnApp
metadata:
  name: podtato-head
  namespace: podtato-kubectl
spec:
  version: "0.1.4"
  workloads:
    - name: podtato-head-frontend
      version: 0.1.4
    - name: podtato-head-hat
      version: 0.1.4
    - name: podtato-head-left-arm
      version: 0.1.4
    - name: podtato-head-right-arm
      version: 0.1.4
    - name: podtato-head-left-leg
      version: 0.1.4
    - name: podtato-head-right-leg
      version: 0.1.4
  preDeploymentTasks:
    - container-sleep
    - python-secret
