resources:
  - https://github.com/podtato-head/podtato-head-app/releases/download/v0.3.3/manifest.yaml
  - app-post-deploy.yaml
  - provider.yaml
  - metric.yaml
  - container-task.yaml
  - python-task.yaml

patchesStrategicMerge:
  - manifest.yaml
