apiVersion: metrics.keptn.sh/v1alpha3
kind: KeptnMetricsProvider
metadata:
  name: my-provider
  namespace: podtato-kubectl
spec:
  type: prometheus
  targetServer: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090"
