---
apiVersion: v1
kind: Namespace
metadata:
  name: podtato-kubectl
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-hat
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        keptn.sh/pre-deployment-tasks: pre-deployment-check-frontend
        app.kubernetes.io/version: 0.1.6

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-leg
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        keptn.sh/pre-deployment-tasks: pre-deployment-check-frontend
        app.kubernetes.io/version: 0.1.7

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-right-leg
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        keptn.sh/pre-deployment-tasks: pre-deployment-check-frontend
        app.kubernetes.io/version: 0.1.8

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-arm
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        keptn.sh/pre-deployment-tasks: pre-deployment-check-frontend
        app.kubernetes.io/version: 0.1.9

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-right-arm
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        keptn.sh/pre-deployment-tasks: pre-deployment-check-frontend
        app.kubernetes.io/version: 0.1.10
